### ISSUE TITLE
A big "Thank You" and an AppImage for testing

### ISSUE THREAD

**Issue by probonopd** [aoloe/scribus-plugin-actionSearch#2]
A big "Thank You" :+1: @aoloe and an [AppImage](https://appimage.org/) for testing this on Linux:

https://gitlab.com/probono/scribus/-/jobs/148886034/artifacts/raw/Scribus-663e770-x86_64.AppImage

**Comment by Chaz6** [comment]
On CentOS 7 (libQt5Core.so.5: cannot open shared object file: No such file or directory)

**Comment by probonopd** [comment]
> If I extract (--appimage-extract) and run with LD_LIBRARY_PATH to usr/lib

That's not a valid way to run _this_ AppImage, because it was built on a _newer_ system than CentOS 7, and bundles _everything_ (at least it should...), down to and including glibc and ld-linux.so. I suspect we missed something that still gets loaded from your base system and then causes the crash. Can you run the extracted AppRun script with `strace -f ./AppRun` and see if you can find out what goes on before the crash?

**Comment by probonopd** [comment]
Action Search since has landed in the regular Scribus application.
